appname: "manwar"

layout: "main"

charset: "UTF-8"

session: Simple

template: "template_toolkit"
engines:
   template:
     template_toolkit:
       start_tag: '<%'
       end_tag:   '%>'

plugins:
   "Map::Tube":
       available_maps: [ "london", "delhi", "barcelon", "kolkatta" ]